name: Generate Pacman Animation

on:
  # Se ejecuta automáticamente cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:
  
  # Se ejecuta automáticamente al hacer push a main
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: infinityxgame
          template: classic
          base: ""
          config_theme: dark
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
